### ISSUE TITLE
'answers' is not one of ['fine-tune'] - 'purpose'

### ISSUE THREAD

**Issue by abunour22** [orhanerday/open-ai#100]
### Describe the bug

I am using :

					$c_file = curl_file_create($file);
					$result =$open_ai->uploadFile([
						"purpose" => "answers",
						"file"    => $c_file,
					]);

Results : 
'answers' is not one of ['fine-tune'] - 'purpose'

### To Reproduce

1. $c_file = curl_file_create($file);
2. $result =$open_ai->uploadFile([
						"purpose" => "answers",
						"file"    => $c_file,
					]);
3. Results : 
'answers' is not one of ['fine-tune'] - 'purpose'

### OS

win

### PHP version

PHP 8

### Library version

openai v3.0.1

**Comment by orhanerday** [comment]
Could you improve the response that you received?
