### ISSUE TITLE
Where are the error codes from the OpenAI documentation ?

### ISSUE THREAD

**Issue by BaptisteAmice** [orhanerday/open-ai#101]
### Describe the feature or improvement you're requesting

Hello,

I would like to know if it's currently possible to get the real OpenAI API error codes, or if this features will be added.

Currently when i call the chat function and get an error it's for example the following : 
```
object(stdClass)#26338 (1) {
  ["error"]=>
  object(stdClass)#26339 (4) {
    ["message"]=>
    string(105) "Incorrect API key provided: 6. You can find your API key at https://platform.openai.com/account/api-keys."
    ["type"]=>
    string(21) "invalid_request_error"
    ["param"]=>
    NULL
    ["code"]=>
    string(15) "invalid_api_key"
  }
}
```

The obtained code is "invalid_api_key", wich isn't the code documented on OpenAI website (401)(https://platform.openai.com/docs/guides/error-codes) and isn't documented anywhere else.

It seem that the code should normally be at the root of the response, but it doesn't seem to be the case.

I thank you in advance for your reply.

**Comment by yassinya** [comment]
Did you figure it out?

**Comment by orhanerday** [comment]
Do you have an API key?

**Comment by BaptisteAmice** [comment]
> Do you have an API key?

Yes I had one, but I finished the related project, sorry for the trouble.

**Comment by orhanerday** [comment]
Sorry for the delayed response. Thanks for the feedback.
