### ISSUE TITLE
Auto-continuing when max_token limit reached

### ISSUE THREAD

**Issue by f00bar** [orhanerday/open-ai#104]
### Describe the feature or improvement you're requesting

Hello,

I'm analysing documents with GPT-4 and often the output exceeds the max tokens limit. In the web version of ChatGPT, when output terminates, a "Continue" button shows up which will restart the output from where it was last cut off.

Is it possible to implement this somehow with this package?

Thanks!

**Comment by orhanerday** [comment]
Hello, 
I couldn't locate the cURL reference. Can you please reopen the issue if you find it?
