### ISSUE TITLE
there is a responsibility for the temperature values

### ISSUE THREAD

**Issue by ob067** [orhanerday/open-ai#105]
### Describe the bug

Merhabalar
ben bir php script aldım. php scripti incelerken içerisinde pluginlerde sizin chatgpt github da paylaştığınız eklenti var

script ise : https://codecanyon.net/item/openai-davinci-ai-writing-assistant-and-content-creator-as-saas/43564164

şimdi benim istediğim şey şu chatgpt ile aynı cevapları vermesi. bunun için de temperature değerlerini değiştirmem gerekiyormuş sanırım bir türlü aynı cevabı alamadım bir de ısı değerlerini değiştirme bölümünü bulamadım. 
Chatgpt ile aynı cevapları almama yardımcı olursan cok cok sevinirim.

Saygılarımla. İyi çalışmalar dilerim

### To Reproduce

burdaki durumu düzenlemek istiyorum özel cpanel bilgileri mailden gönderildi

### OS

windows

### PHP version

7.4

### Library version

gpt 3.5

**Comment by orhanerday** [comment]
Tüm kodda `tempeture` kelimesini arar mısın? 

Bu tarz bir şey bulman gerekiyor
` 'temperature' => 1.0,`

Eğer içinden çıkamazsan bionluk vs'den bir php dev tutmanı öneririm. Ben 1:1 destek veremiyorum.

Bu arada satış linkini gönderdiğin için teşekkür ediyorum, bu tür popüler SaaS uygulamalasında kütühanemin geçmesi beni mutlu etti.
