### ISSUE TITLE
text-davinci-003 is deprecated

### ISSUE THREAD

**Issue by sixdaystudio** [orhanerday/open-ai#108]
When making a request using `o1penAI->completion`, I receive the following message: 

> This model version is deprecated. Migrate before January 4, 2024 to avoid disruption of service. Learn more https://platform.openai.com/docs/deprecations.

I tried to change the model to `gpt-3.5-turbo`, but I receive a message stating that the model is only for chat. Starting in 2024, the deprecated model will no longer be available. 

How will the call to the completion endpoint look like starting in 2024?

Below is an image of what I receive when making the request.
![image](https://github.com/orhanerday/open-ai/assets/6549506/56ff5abe-0e99-4254-9db6-c9b3917a069a)

**Comment by orhanerday** [comment]
Could you change model to `gpt-3.5-turbo-instruct`?

**Comment by orhanerday** [comment]
FYI, I also edit the readme. I appreciate your info.
