### ISSUE TITLE
The data returned is confusing when use stream

### ISSUE THREAD

**Issue by muzilong** [orhanerday/open-ai#109]
### Describe the bug

when i Log::info $data like this

```php
$this->openAi->chat([
                'model' => 'gpt-3.5-turbo-16k',
                'messages' => $temp,
                'temperature' => 1.0,
                'max_tokens' => 3000,
                'frequency_penalty' => 0,
                'presence_penalty' => 0,
                'stream' => true
            ], function ($curl_info, $data) use ($gptArticle) {
                Log::info($data);
```

Sometimes it is correct：

```
[2023-10-12 10:05:02] local.INFO: data: {"id":"chatcmpl-88fLfcuOH33GOKQ49iq2vXAuzCHZQ","object":"chat.completion.chunk","created":1697076259,"model":"gpt-3.5-turbo-16k-0613","choices":[{"index":0,"delta":{"content":" air"},"finish_reason":null}]}


[2023-10-12 10:05:02] local.INFO: data: {"id":"chatcmpl-88fLfcuOH33GOKQ49iq2vXAuzCHZQ","object":"chat.completion.chunk","created":1697076259,"model":"gpt-3.5-turbo-16k-0613","choices":[{"index":0,"delta":{"content":" compressor"},"finish_reason":null}]}


[2023-10-12 10:05:02] local.INFO: data: {"id":"chatcmpl-88fLfcuOH33GOKQ49iq2vXAuzCHZQ","object":"chat.completion.chunk","created":1697076259,"model":"gpt-3.5-turbo-16k-0613","choices":[{"index":0,"delta":{"content":" guarantees"},"finish_reason":null}]}


[2023-10-12 10:05:02] local.INFO: data: {"id":"chatcmpl-88fLfcuOH33GOKQ49iq2vXAuzCHZQ","object":"chat.completion.chunk","created":1697076259,"model":"gpt-3.5-turbo-16k-0613","choices":[{"index":0,"delta":{"content":" the"},"finish_reason":null}]}


[2023-10-12 10:05:02] local.INFO: data: {"id":"chatcmpl-88fLfcuOH33GOKQ49iq2vXAuzCHZQ","object":"chat.completion.chunk","created":1697076259,"model":"gpt-3.5-turbo-16k-0613","choices":[{"index":0,"delta":{"content":" highest"},"finish_reason":null}]}


[2023-10-12 10:05:02] local.INFO: data: {"id":"chatcmpl-88fLfcuOH33GOKQ49iq2vXAuzCHZQ","object":"chat.completion.chunk","created":1697076259,"model":"gpt-3.5-turbo-16k-0613","choices":[{"index":0,"delta":{"content":" standard"},"finish_reason":null}]}


```

Sometimes it is trouble：

```
[2023-10-12 09:45:10] local.INFO: data: {"id":"chatcmpl-88f382uaVhRbGxjRK8xW2MsNW4832","object":"chat.completion.chunk","created":1697075110,"model":"gpt-3.5-turbo-16k-0613","c  
[2023-10-12 09:45:11] local.INFO: hoices":[{"index":0,"delta":{"role":"assistant","content":""},"finish_reason":null}]}

data: {"id":"chatcmpl-88f382uaVhRbGxjRK8xW2MsNW4832","object":"chat.completion.chunk","created":1697075110,"model":"gpt-3.5-turbo
[2023-10-12 09:45:11] local.INFO: -16k-0613","choices":[{"index":0,"delta":{"content":"#"},"finish_reason":null}]}

data: {"id":"chatcmpl-88f382uaVhRbGxjRK8xW2MsNW4832","object":"chat.completion.chunk","created":1697075110,"model":"gpt-3.5-turbo-16k
[2023-10-12 09:45:11] local.INFO: -0613","choices":[{"index":0,"delta":{"content":" The"},"finish_reason":null}]}

data: {"id":"chatcmpl-88f382uaVhRbGxjRK8xW2MsNW4832","object":"chat.completion.chunk","created":1697075110,"model":"gpt-3.5-turbo-16  
[2023-10-12 09:45:11] local.INFO: k-0613","choices":[{"index":0,"delta":{"content":" Power"},"finish_reason":null}]}

data: {"id":"chatcmpl-88f382uaVhRbGxjRK8xW2MsNW4832","object":"chat.completion.chunk","created":1697075110,"model":"gpt-3.5-turbo-16k-061
[2023-10-12 09:45:11] local.INFO: 3","choices":[{"index":0,"delta":{"content":"house"},"finish_reason":null}]}

data: {"id":"chatcmpl-88f382uaVhRbGxjRK8xW2MsNW4832","object":"chat.completion.chunk","created":1697075110,"model":"gpt-3.5-turbo-16k  
[2023-10-12 09:45:11] local.INFO: -0613","choices":[{"index":0,"delta":{"content":" of"},"finish_reason":null}]}

data: {"id":"chatcmpl-88f382uaVhRbGxjRK8xW2MsNW4832","object":"chat.completion.chunk","created":1697075110,"model":"gpt-3.5-turbo-16k
[2023-10-12 09:45:11] local.INFO: -0613","choices":[{"index":0,"delta":{"content":" Efficiency"},"finish_reason":null}]}

data: {"id":"chatcmpl-88f382uaVhRbGxjRK8xW2MsNW4832","object":"chat.completion.chunk","created":1697075110,"model":"gpt-3.5-  
[2023-10-12 09:45:11] local.INFO: turbo-16k-0613","choices":[{"index":0,"delta":{"content":":"},"finish_reason":null}]}

data: {"id":"chatcmpl-88f382uaVhRbGxjRK8xW2MsNW4832","object":"chat.completion.chunk","created":1697075110,"model":"gpt-3.5-turbo
[2023-10-12 09:45:11] local.INFO: -16k-0613","choices":[{"index":0,"delta":{"content":" Un"},"finish_reason":null}]}
```

Very confused

### To Reproduce

null

### OS

Ubuntu 20.04.5 LTS x86_64

### PHP version

8.1.19

### Library version

4.8

**Comment by xing61** [comment]
I found this too，any solution？？

**Comment by orhanerday** [comment]
Try with `'gpt-3.5-turbo'`.

**Comment by orhanerday** [comment]
Could you please try the same request using the official [OpenAI Python library](https://github.com/openai/openai-python)? If there are no issues with Python and an issue exists with the PHP library, please reopen the ticket.

Py code should be like this:
````
response = openai.ChatCompletion.create(
    model="gpt-3.5-turbo-16k",
    messages=[
        {"role": "system", "content": "You are a helpful assistant."},
        {"role": "user", "content": "Who won the world series in 2020?"},
        {"role": "assistant", "content": "The Los Angeles Dodgers won the World Series in 2020."},
        {"role": "user", "content": "Where was it played?"}
    ]
)
````

**Comment by pingfuwei** [comment]
> ### 描述错误
> 当我像这样 Log::info $data 时
> 
> ```
> $this->openAi->chat([
>                 'model' => 'gpt-3.5-turbo-16k',
>                 'messages' => $temp,
>                 'temperature' => 1.0,
>                 'max_tokens' => 3000,
>                 'frequency_penalty' => 0,
>                 'presence_penalty' => 0,
>                 'stream' => true
>             ], function ($curl_info, $data) use ($gptArticle) {
>                 Log::info($data);
> ```
> 
> 有时是正确的：
> 
> ```
> [2023-10-12 10:05:02] local.INFO: data: {"id":"chatcmpl-88fLfcuOH33GOKQ49iq2vXAuzCHZQ","object":"chat.completion.chunk","created":1697076259,"model":"gpt-3.5-turbo-16k-0613","choices":[{"index":0,"delta":{"content":" air"},"finish_reason":null}]}
> 
> 
> [2023-10-12 10:05:02] local.INFO: data: {"id":"chatcmpl-88fLfcuOH33GOKQ49iq2vXAuzCHZQ","object":"chat.completion.chunk","created":1697076259,"model":"gpt-3.5-turbo-16k-0613","choices":[{"index":0,"delta":{"content":" compressor"},"finish_reason":null}]}
> 
> 
> [2023-10-12 10:05:02] local.INFO: data: {"id":"chatcmpl-88fLfcuOH33GOKQ49iq2vXAuzCHZQ","object":"chat.completion.chunk","created":1697076259,"model":"gpt-3.5-turbo-16k-0613","choices":[{"index":0,"delta":{"content":" guarantees"},"finish_reason":null}]}
> 
> 
> [2023-10-12 10:05:02] local.INFO: data: {"id":"chatcmpl-88fLfcuOH33GOKQ49iq2vXAuzCHZQ","object":"chat.completion.chunk","created":1697076259,"model":"gpt-3.5-turbo-16k-0613","choices":[{"index":0,"delta":{"content":" the"},"finish_reason":null}]}
> 
> 
> [2023-10-12 10:05:02] local.INFO: data: {"id":"chatcmpl-88fLfcuOH33GOKQ49iq2vXAuzCHZQ","object":"chat.completion.chunk","created":1697076259,"model":"gpt-3.5-turbo-16k-0613","choices":[{"index":0,"delta":{"content":" highest"},"finish_reason":null}]}
> 
> 
> [2023-10-12 10:05:02] local.INFO: data: {"id":"chatcmpl-88fLfcuOH33GOKQ49iq2vXAuzCHZQ","object":"chat.completion.chunk","created":1697076259,"model":"gpt-3.5-turbo-16k-0613","choices":[{"index":0,"delta":{"content":" standard"},"finish_reason":null}]}
> ```
> 
> 有时候很麻烦：
> 
> ```
> [2023-10-12 09:45:10] local.INFO: data: {"id":"chatcmpl-88f382uaVhRbGxjRK8xW2MsNW4832","object":"chat.completion.chunk","created":1697075110,"model":"gpt-3.5-turbo-16k-0613","c  
> [2023-10-12 09:45:11] local.INFO: hoices":[{"index":0,"delta":{"role":"assistant","content":""},"finish_reason":null}]}
> 
> data: {"id":"chatcmpl-88f382uaVhRbGxjRK8xW2MsNW4832","object":"chat.completion.chunk","created":1697075110,"model":"gpt-3.5-turbo
> [2023-10-12 09:45:11] local.INFO: -16k-0613","choices":[{"index":0,"delta":{"content":"#"},"finish_reason":null}]}
> 
> data: {"id":"chatcmpl-88f382uaVhRbGxjRK8xW2MsNW4832","object":"chat.completion.chunk","created":1697075110,"model":"gpt-3.5-turbo-16k
> [2023-10-12 09:45:11] local.INFO: -0613","choices":[{"index":0,"delta":{"content":" The"},"finish_reason":null}]}
> 
> data: {"id":"chatcmpl-88f382uaVhRbGxjRK8xW2MsNW4832","object":"chat.completion.chunk","created":1697075110,"model":"gpt-3.5-turbo-16  
> [2023-10-12 09:45:11] local.INFO: k-0613","choices":[{"index":0,"delta":{"content":" Power"},"finish_reason":null}]}
> 
> data: {"id":"chatcmpl-88f382uaVhRbGxjRK8xW2MsNW4832","object":"chat.completion.chunk","created":1697075110,"model":"gpt-3.5-turbo-16k-061
> [2023-10-12 09:45:11] local.INFO: 3","choices":[{"index":0,"delta":{"content":"house"},"finish_reason":null}]}
> 
> data: {"id":"chatcmpl-88f382uaVhRbGxjRK8xW2MsNW4832","object":"chat.completion.chunk","created":1697075110,"model":"gpt-3.5-turbo-16k  
> [2023-10-12 09:45:11] local.INFO: -0613","choices":[{"index":0,"delta":{"content":" of"},"finish_reason":null}]}
> 
> data: {"id":"chatcmpl-88f382uaVhRbGxjRK8xW2MsNW4832","object":"chat.completion.chunk","created":1697075110,"model":"gpt-3.5-turbo-16k
> [2023-10-12 09:45:11] local.INFO: -0613","choices":[{"index":0,"delta":{"content":" Efficiency"},"finish_reason":null}]}
> 
> data: {"id":"chatcmpl-88f382uaVhRbGxjRK8xW2MsNW4832","object":"chat.completion.chunk","created":1697075110,"model":"gpt-3.5-  
> [2023-10-12 09:45:11] local.INFO: turbo-16k-0613","choices":[{"index":0,"delta":{"content":":"},"finish_reason":null}]}
> 
> data: {"id":"chatcmpl-88f382uaVhRbGxjRK8xW2MsNW4832","object":"chat.completion.chunk","created":1697075110,"model":"gpt-3.5-turbo
> [2023-10-12 09:45:11] local.INFO: -16k-0613","choices":[{"index":0,"delta":{"content":" Un"},"finish_reason":null}]}
> ```
> 
> 很困惑
> 
> ### 重现
> 无效的
> 
> ### 代码片段
> _没有反应_
> 
> ### 操作系统
> Ubuntu 20.04.5 LTS x86_64
> 
> ### PHP版本
> 8.1.19
> 
> ### 库版本
> 4.8

Hello, has this problem been resolved

**Comment by pingfuwei** [comment]
@orhanerday Hello, has this problem been resolved，

**Comment by orhanerday** [comment]
@pingfuwei did you try on Python package with the same request?

**Comment by pingfuwei** [comment]
The project is for PHP development, and I need to find a solution for PHP









------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "orhanerday/open-ai"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年11月9日(星期四) 下午4:14
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [orhanerday/open-ai] The data returned is confusing when use stream (Issue #109)





 
@pingfuwei did you try on Python package with the same request?

**Comment by orhanerday** [comment]
If you got the same issue on python package, it is OpenAI related issue.

**Comment by muzilong** [comment]
I'm sorry for not giving timely feedback.

Yeah, it is OpenAI related issue.

When I reported the problem, openai was in trouble.

When openai fixed the problem everything was resolved.

thank you all the same

**Comment by iamaz007** [comment]
This bug still not resolved yet by OpenAi

For now, I have resolved it using regex, I'm extracting content directly from respone.

```
// Define the pattern to match
$pattern = '/"choices":\[\{"index":0,"delta":\{"content":"(.*?)"\}/';

// Use preg_match_all to find all matches
preg_match_all($pattern, $inputData, $matches);

// Extract content from the matches
$contents = $matches[1];
```

**Comment by orhanerday** [comment]
Hi @iamaz007 
Did you contact OpenAI?

**Comment by iamaz007** [comment]
Nope, they don't even reply for hours.

I tested libraries, in Flutter, that issue is happening there too. so, for now we have to solve it on our own.

**Comment by orhanerday** [comment]
Could you please ask this question on the [OpenAI form](https://community.openai.com)? Maybe we can get better help from the community.

Please drop the post link over here. Thank you!
