### ISSUE TITLE
ChatGPT request very slowly, up to 2-3 mins

### ISSUE THREAD

**Issue by NDanilov2015** [orhanerday/open-ai#110]
### Describe the bug

We got stuck with abruptly decrease velocity of work chatgpt with any buyed accounts.

Such requests give more 1 min since October 2023:

	$chat = $open_ai->chat([
		   'model' => 'gpt-3.5-turbo',
		   'messages' => [
			   [
					'role' => 'system',
					'content' => 'Message 1',
				],
				[
					'role' => 'user',
					'content' => 'Message 2',
				]
		   ],
		   'temperature' => 0.5,
		   'max_tokens' => 3700,
		   'frequency_penalty' => 0,
		   'presence_penalty' => 0,
		]);

### To Reproduce

Simple try chat mode.

### Code snippets

```JavaScript
$chat = $open_ai->chat([
		   'model' => 'gpt-3.5-turbo',
		   'messages' => [
			   [
					'role' => 'system',
					'content' => 'Message 1',
				],
				[
					'role' => 'user',
					'content' => 'Message 2',
				]
		   ],
		   'temperature' => 0.5,
		   'max_tokens' => 3700,
		   'frequency_penalty' => 0,
		   'presence_penalty' => 0,
		]);
```

### OS

Ubuntu 22.02

### PHP version

PHP 7.4

### Library version

openai v3.5

**Comment by orhanerday** [comment]
Hello @NDanilov2015,

Could send a cURL the same request with Postman?


````
curl https://api.openai.com/v1/chat/completions \
  -H "Content-Type: application/json" \
  -H "Authorization: Bearer $OPENAI_API_KEY" \
  -d '{
    "model": "gpt-3.5-turbo",
    "messages": [
      {
        "role": "system",
        "content": "You are a helpful assistant."
      },
      {
        "role": "user",
        "content": "Hello!"
      }
    ]
  }'

````

> Please edit the request according to your code. I pasted it from the OpenAI API reference webpage.

If you got the same delayed result, please contact OpenAI. If there is a response delay; please reopen the issue. I'll take care.

**Comment by CxRxExO** [comment]
test the new model `gpt-3.5-turbo-1106` 👍
