### ISSUE TITLE
New Assistants API support?

### ISSUE THREAD

**Issue by aleibovici** [orhanerday/open-ai#115]
### Describe the feature or improvement you're requesting

Assistants looks fantastic, specially the ability to have persistent threads and work with files. Plans to implement the API?

**Comment by orhanerday** [comment]
I couldn't locate the cURL reference. Can you please reopen the issue if you find it?

**Comment by aman811** [comment]
@orhanerday Is this the link you require?
https://platform.openai.com/docs/api-reference/assistants/createAssistant

**Comment by orhanerday** [comment]
I reopened it. Thanks!

**Comment by informaticavera** [comment]
good idea, thanks for your work

**Comment by orhanerday** [comment]
Greetings, @joacir 

Please do. I’m quite occupied lately. 

Your time and effort are greatly appreciated.

**Comment by riteshjha** [comment]
Hey, @joacir let me know when you start and if i can help.

**Comment by orhanerday** [comment]
I merged the PR, You ROCK @joacir!

**Comment by orhanerday** [comment]
@riteshjha, 5.0 has been released, execute `composer update`, 

Also please feel free to review the relevant [pr](https://github.com/orhanerday/open-ai/pull/130).

**Comment by riteshjha** [comment]
awesome @orhanerday

**Comment by aleibovici** [comment]
Fantastic! I'll test it.... Thanks.
