### ISSUE TITLE
Model returning false

### ISSUE THREAD

**Issue by geosemaan** [orhanerday/open-ai#12]
Hi there, I'm trying to set up a working example using Laravel but when I `dd($complete)` I get `false`.

```
namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Orhanerday\OpenAi\OpenAi;

class HomeController extends Controller
{
    public function index() {
        $open_ai = new OpenAi(env('OPEN_AI_API_KEY'));
        $engines = $open_ai->engines();

        $complete = $open_ai->complete([
            'engine' => 'davinci',
            'prompt' => 'Hello',
            'temperature' => 0.9,
            'max_tokens' => 150,
            'frequency_penalty' => 0,
            'presence_penalty' => 0.6,
        ]);

        $data = json_decode($complete, true);

        dd($engines);
    }
}
```
`$open_ai` returns a collection with `engine`, `headers` and `contentTypes`

`$engines` returns false as well, it's not even reading the library.

`$data` returns `null`

**Comment by orhanerday** [comment]
I test on my local _(Laravel v9.17.0 (PHP v8.1.6)_, and I didn't find any issue like that. 

So I just returned `$engines`
![image](https://user-images.githubusercontent.com/22305274/174442639-cf8aa466-71cc-4b77-955d-798ab23ef63a.png)
Returned `$data`
![image](https://user-images.githubusercontent.com/22305274/174442660-bad29f31-134f-4df9-a5ec-f10c58ad5468.png)

I don't recommend using dd, because they didn't have a friendly JSON format, return data then use  [JSON viewer](https://chrome.google.com/webstore/detail/json-viewer/gbmdgpbipfallnflgajpaliibnhdgobh) instead of.

### TROUBLESHOOTING
- Did you install the package with `composer install orhanerday/open-ai` ?
- Please check your [OpenAI credit](https://beta.openai.com/account/usage).
- You should get an error when providing a wrong API key, just in case; check your API key twice.

**Comment by geosemaan** [comment]
I am stumped. I get a blank page when I `return $data` or `return $engines`.

Yes, I have installed `orhanerday/open-ai` and I have plenty of credits in my account.

But what's weird is that I am not getting an error when I put a wrong API key.

**Comment by orhanerday** [comment]
Could you please run the following curl command?
```
curl https://api.openai.com/v1/completions \
  -H 'Content-Type: application/json' \
  -H 'Authorization: Bearer YOUR_API_KEY' \
  -d '{
  "model": "text-davinci-002",
  "prompt": "Say this is a test",
  "max_tokens": 5
}'
```
You should see response like this;
```
{
  "id": "cmpl-uqkvlQyYK7bGYrRHQ0eXlWi7",
  "object": "text_completion",
  "created": 1589478378,
  "model": "text-davinci-002",
  "choices": [
    {
      "text": "\n\nThis is a test",
      "index": 0,
      "logprobs": null,
      "finish_reason": "length"
    }
  ]
}
```

I just wanna check if you can easily access open-ai servers.
After that, I need your PHP, cURL, and laravel versions.

For getting the cURL version, put the following code to your index function;

```
public function index(){
      return function_exists('curl_version');
...
```

**Comment by geosemaan** [comment]
The curl command works in gitbash

![curl](https://user-images.githubusercontent.com/3442636/174445891-c9ffa623-aad9-4b1a-9547-f0d804be3f96.png)

`function_exists('curl_version')` returns 1
Curl version is 7.79.1
Laravel version 9.17.0

**Comment by orhanerday** [comment]
I didn't catch any reason for the bug. So I prepare another troubleshooting

- lets pretty sure our curl is working. For this, put code your PHP file
```

// From URL to get webpage contents.
$url = "https://www.geeksforgeeks.org/";
 
// Initialize a CURL session.
$ch = curl_init();
 
// Return Page contents.
curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
 
//grab URL and pass it to the variable.
curl_setopt($ch, CURLOPT_URL, $url);
 
$result = curl_exec($ch);
 
echo $result; 

```
Did you see the gfg page?
- Also can you install laravel with [docker](https://laravel.com/docs/9.x#getting-started-on-windows)?

**Comment by geosemaan** [comment]
I am still getting a blank page.

Very weird, because `curl -V` works.

I am downloading Docker Desktop but I've never used it before.

**Comment by orhanerday** [comment]
I think cURL is disabled in PHP, for enabling can you apply these steps?

- Open php.ini (it’s usually in /etc/ or in the PHP folder on the server).
- Search for extension=php_curl.dll. Uncomment it by removing the semi-colon( ; ) in front of it.
- Restart the Apache Server.

**Comment by geosemaan** [comment]
Thank you for taking the time to help me out, I appreciate it.

`extension=curl` was uncommented, I changed it to `php_curl` and `php_curl.dll` but got the same blank page.

Also please note I am using wampserver and curl is enabled 

![wampserver](https://user-images.githubusercontent.com/3442636/174448576-8fee866a-1bd5-4950-bea3-9acfcf7e057d.png)

**Comment by orhanerday** [comment]
That's great to hear that! I wish you to develop great projects.

**Comment by geosemaan** [comment]
I think you misunderstood, I'm still unable to access the API even though curl is installed.
It's still not working.

**Comment by orhanerday** [comment]
Sorry about that, Let's try with Docker then. I'll be waiting for your response.

**Comment by geosemaan** [comment]
It finally worked! I got curl to finally work.

Thank you for your patience, I can't wait to see the limits of this library.

**Comment by orhanerday** [comment]
That's great to hear that!  it's not boring, so I don't need any patience :). I feel glad while helping you guys.

Have a great day!

**Comment by silicahd** [comment]
> return function_exists('curl_version');

How did you fix this issue? I have been going at it for about two days and I am getting the same thing on multiple systems.

**Comment by silicahd** [comment]
> 

I think there might be an issue, because the code you posted does not work. But this code works. 

https://www.plus2net.com/php_tutorial/curl-demo.php

**Comment by silicahd** [comment]
> I didn't catch any reason for the bug. So I prepare another troubleshooting
> 
> * lets pretty sure our curl is working. For this, put code your PHP file
> 
> ```
> 
> // From URL to get webpage contents.
> $url = "https://www.geeksforgeeks.org/";
>  
> // Initialize a CURL session.
> $ch = curl_init();
>  
> // Return Page contents.
> curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
>  
> //grab URL and pass it to the variable.
> curl_setopt($ch, CURLOPT_URL, $url);
>  
> $result = curl_exec($ch);
>  
> echo $result; 
> ```
> 
> Did you see the gfg page?
> 
> * Also can you install laravel with [docker](https://laravel.com/docs/9.x#getting-started-on-windows)?

I think there might be an issue, because the code you posted does not work. But this code works. 

https://www.plus2net.com/php_tutorial/curl-demo.php

**Comment by silicahd** [comment]
> I didn't catch any reason for the bug. So I prepare another troubleshooting
> 
> * lets pretty sure our curl is working. For this, put code your PHP file
> 
> ```
> 
> // From URL to get webpage contents.
> $url = "https://www.geeksforgeeks.org/";
>  
> // Initialize a CURL session.
> $ch = curl_init();
>  
> // Return Page contents.
> curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
>  
> //grab URL and pass it to the variable.
> curl_setopt($ch, CURLOPT_URL, $url);
>  
> $result = curl_exec($ch);
>  
> echo $result; 
> ```
> 
> Did you see the gfg page?
> 
> * Also can you install laravel with [docker](https://laravel.com/docs/9.x#getting-started-on-windows)?

This is so odd. The code you posted does not work. 
`            $url = 'https://api.plos.org/search?q=title:DNA';
            $ch = curl_init();
            curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
            curl_setopt($ch, CURLOPT_HTTPHEADER,     array(
                'Authorization: Bearer API CODE HERE'
                ));
            curl_setopt($ch, CURLOPT_URL,$url);
            $result=curl_exec($ch);
            curl_close($ch);
            return $result;`

This code works just fine 

            $url = 'https://api.plos.org/search?q=title:DNA';
            $ch = curl_init();
            curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
            curl_setopt($ch, CURLOPT_HTTPHEADER,     array(
                'Authorization: Bearer API CODE HERE'
                ));
            curl_setopt($ch, CURLOPT_URL,$url);
            $result=curl_exec($ch);
            curl_close($ch);
            return $result;

But if i change the URL to 
https://api.openai.com/v1/models  
and add my api it will return null 

The odd thing is that i can test this via Postman or Curl terminal with no issues. I am sure this is not something on the code side but i just cant figure this out it baffles me.

**Comment by orhanerday** [comment]
hey @silicahd create an _index.php_ and could you try this example.

```
<?php

require __DIR__ . '/vendor/autoload.php'; // remove this line if you use a PHP Framework.

use Orhanerday\OpenAi\OpenAi;

$open_ai = new OpenAi('sk-gjtv.....');

$complete = $open_ai->complete([
    'engine' => 'davinci',
    'prompt' => 'Hello',
    'temperature' => 0.9,
    'max_tokens' => 150,
    'frequency_penalty' => 0,
    'presence_penalty' => 0.6,
]);

var_dump($complete);
```

**Comment by silicahd** [comment]
> hey @silicahd, could you create an _index.php_ and put following example.
> 
> ```
> <?php
> 
> require __DIR__ . '/vendor/autoload.php'; 
> 
> use Orhanerday\OpenAi\OpenAi;
> 
> $open_ai = new OpenAi('sk-gjtv.....');
> 
> $complete = $open_ai->complete([
>     'engine' => 'davinci',
>     'prompt' => 'Hello',
>     'temperature' => 0.9,
>     'max_tokens' => 150,
>     'frequency_penalty' => 0,
>     'presence_penalty' => 0.6,
> ]);
> 
> var_dump($complete);
> ```
> 
> can you share your response?

I found the issue but cant figure out how to fix it. I add the line to get the error from Curl and it came back to "SSL certificate problem: certificate has expired"  . My SSL is there so i am trying to figure out if we can do insecure so figure out why CURL gives this response.

**Comment by silicahd** [comment]
For anybody running into this if you are using something like aaPanel or others likely your certificate is expired. 

Credit to this fix to the guys from the aaPanel forum. 
@orhanerday thank you for the support and the amazing package.

`
mkdir -p /etc/pki/tls/certs
wget -O /etc/pki/tls/certs/ca-bundle.crt https://curl.se/ca/cacert.pem --no-check-certificate
chmod 444 /etc/pki/tls/certs/ca-bundle.crt`

**Comment by orhanerday** [comment]
Thanks so much,

I hope you can solve the certificate problem as soon as possible.

Regards.

**Comment by orhanerday** [comment]
I'm so glad for everything solved out. Also thank you so much for good wishes.

**Comment by davidblanco-m** [comment]
Hello,

Had the same issue, it seems to be related to the SSL certificate as @silicahd mentioned, I managed to get around it by adding the following flags in the $curl_info variable:

```
CURLOPT_SSL_VERIFYPEER => false,
CURLOPT_SSL_VERIFYHOST => false,
```

at the end of the open-ai/src/OpenAi.php file

**Comment by bdkoder** [comment]
> Hello,
> 
> Had the same issue, it seems to be related to the SSL certificate as @silicahd mentioned, I managed to get around it by adding the following flags in the $curl_info variable:
> 
> ```
> CURLOPT_SSL_VERIFYPEER => false,
> CURLOPT_SSL_VERIFYHOST => false,
> ```
> 
> at the end of the open-ai/src/OpenAi.php file
> 
> thank you @orhanerday for this amazing repo 👍

Thank you very much. It's saved me hours of time.
