### ISSUE TITLE
Cannot execute tts (Text to spech)

### ISSUE THREAD

**Issue by tobiasredel** [orhanerday/open-ai#134]
### Describe the bug

Call to undefined method Orhanerday\OpenAi\OpenAi::tts()

### To Reproduce

Try to run openai::tts

### OS

macos

### PHP version

php 7

### Library version

openai 4.9

**Comment by orhanerday** [comment]
Did you execute 'composer update orhanerday/open-ai' ?

**Comment by orhanerday** [comment]
Sorry, I didn't quite catch, is it worked or not? If not, could you provide your code?

**Comment by tobiasredel** [comment]
No

Code / function is:

private static function calculateSpeech($text, $voice = 'shimmer'){
        $open_ai_key = getenv('OPENAI_API_KEY');
        $open_ai = new OpenAi($open_ai_key);
        $result = $open_ai->tts([
            "model" => "tts-1", // tts-1-hd
            "input" => $text,
            "voice" => $voice, // echo, fable, onyx, nova, and shimmer
        ]);

        $uniqueId = uniqid();
        $fileName = 'grass_'.$event->id.'_'.$uniqueId.'.mp3'; // You can customize the file name
        Storage::put('public/voices/events/'.$fileName, $result);

        // Save link in the database
        return 'storage/public/voices/events/'.$fileName;
    }

**Comment by orhanerday** [comment]
I need the composer.json, could you provide it?

**Comment by tobiasredel** [comment]
Here is the part where openai is imported

{
    "name": "laravel/laravel",
    "type": "project",
    "description": "The skeleton application for the Laravel framework.",
    "keywords": ["laravel", "framework"],
    "license": "MIT",
    "require": {
        "php": "^8.1",
        "guzzlehttp/guzzle": "^7.2",
        "laravel/framework": "^10.10",
        "laravel/sanctum": "^3.2",
        "laravel/tinker": "^2.8",
        "laravelcollective/html": "^6.4",
        "orhanerday/open-ai": "^4.9"
    },
    "require-dev": {
        "fakerphp/faker": "^1.9.1",
        "laravel/breeze": "^1.23",
        "laravel/pint": "^1.0",
        "laravel/sail": "^1.18",
        "laravel/ui": "^4.3",
        "mockery/mockery": "^1.4.4",
        "nunomaduro/collision": "^7.0",
        "phpunit/phpunit": "^10.1",
        "spatie/laravel-ignition": "^2.0"
    },

**Comment by orhanerday** [comment]
You are using "orhanerday/open-ai": "^4.9". It should be "orhanerday/open-ai": "^5.1"


Please upgrade it.

**Comment by tobiasredel** [comment]
Thank you so much
