### ISSUE TITLE
OpenAI-Beta: assistants=v2

### ISSUE THREAD

**Issue by thomasdv** [orhanerday/open-ai#140]
### Describe the bug

New Assistants API requires the `OpenAI-Beta: assistants=v2` header. However it seems `v1` is hardcoded in the library. 

API now returns "The requested model 'gpt-4o' cannot be used with the Assistants API in v1. Follow the migration guide to upgrade to v2: https://platform.openai.com/docs/assistants/migration."

### To Reproduce

Send request to any of the Assistants endpoint with gpt-4o model.

### OS

Any

### PHP version

Any

### Library version

5.1

**Comment by orhanerday** [comment]
If it's possible, could open a pr for this issue? 

Thanks.

**Comment by orhanerday** [comment]
Sorry for the delay, thank you soo much.
