### ISSUE TITLE
Add support for content-filter

### ISSUE THREAD

**Issue by jason-engage** [orhanerday/open-ai#15]
Can you please add support for this?: https://beta.openai.com/docs/models/content-filter

**Comment by jason-engage** [comment]
Yeah I tried that, but it gives an error saying that you can't have both an engine and a model at the same time (even though the engine isn't provided). I think you're building the url path using "/engines/$engine/completions" which may be causing the conflict.

**Comment by orhanerday** [comment]
Oh ok, I got the conflict right now. Are you need this feature immediately? I need to redesign my plans according to your answer.  🙂

**Comment by jason-engage** [comment]
Well, I'm currently building a new tool in my app, and I want the new tool to go live by next week. I believe the content filter must be implemented before I submit it to openai. So I can safely wait a few days before I need to hook this piece in...  It would be awesome if you can make the mods soonish... Not trying to rush you tho! 🙏

**Comment by orhanerday** [comment]
Hey Jason, I investigate the issue, the content filter and completions seem to use the same URL but it's not. So I'm gonna implement to new URl structure I can done the feature about 1 week. FYI.

**Comment by jason-engage** [comment]
Hi, have you had the chance to make some updates?

**Comment by AbdelbassetD** [comment]
This is late, but here is a quick hack (you need to modify the source files) to get the content-filter working.

In the Url class (Url.php file), create a new method that returns the content-filter API URI (which is simply https://api.openai.com/v1/completions).
```php
/**
 * @return string
 */
public static function contentFilterURL(): string
{
    return self::OPEN_AI_URL . "/completions";
}
```
Then, in the OpenAi class (OpenAi.php file), modify the completion method to become as follows:
```php
/**
 * @param $opts
 * @param $cf
 * @return bool|string
 */
public function complete($opts, $cf = false)
{
    $engine = $opts['engine'] ?? $this->engine;
    $url = $cf ? Url::contentFilterURL() : Url::completionURL($engine);
    unset($opts['engine']);

    return $this->sendRequest($url, 'POST', $opts);
}
```

**Usage:**
```php
$open_ai = new OpenAi('YOUR OPENAI API KEY');
$content= "This is just a sample sentence for testing.";

$filter = $open_ai->complete([
    'model' => 'content-filter-alpha',
    'prompt' => "<|endoftext|>{$content}\n--\nLabel:é,
    'temperature' => 0,
    'max_tokens' => 1,
    'top_p' => 0,
    'logprobs' => 10
], true);

$response = json_decode($filter, true);
$output = $response['choices'][0]['text']; // returns "0", "1", or "2"
```

Of course, this is just a hack and is not production-ready.

**Comment by jason-engage** [comment]
Here's the Unsafe calculation function they offer in python translated into php if anyone wants it: (let me know if there's a mistake!)
https://beta.openai.com/docs/models/content-filter

`function openAiContentFilterUnsafe($response) {

    $output_label = $response['choices'][0]['text']; // returns "0", "1", or "2"

    $toxic_threshold = -0.355;

    if ($output_label == "2") {
        # If the model returns "2", return its confidence in 2 or other output-labels
        $logprobs = $response["choices"][0]["logprobs"]["top_logprobs"][0];

        # If the model is not sufficiently confident in "2",
        # choose the most probable of "0" or "1"
        # Guaranteed to have a confidence for 2 since this was the selected token.
        if ($logprobs["2"] < $toxic_threshold) {
            $logprob_0 = $logprobs["0"] ?? false;
            $logprob_1 = $logprobs["1"] ?? false;

            # If both "0" and "1" have probabilities, set the output label
            # to whichever is most probable
            if (!empty($logprob_0) && !empty($logprob_1)) {
                if ($logprob_0 >= $logprob_1) {
                    $output_label = "0";
                } else {
                    $output_label = "1";
                }
            # If only one of them is found, set output label to that one
            } else if ( !empty($logprob_0) ) {
                $output_label = "0";
            } else if ( !empty($logprob_1) ) {
                $output_label = "1";
            }
            # If neither "0" or "1" are available, stick with "2"
            # by leaving output_label unchanged.
        }
    }

    # if the most probable token is none of "0", "1", or "2"
    # this should be set as unsafe
    if (!in_array($output_label,["0", "1", "2"])) {
        $output_label = "2";
    }

    return $output_label;
}`
