### ISSUE TITLE
Error : Could not resolve: api.openai.com (Could not contact DNS servers)

### ISSUE THREAD

**Issue by gregoirepuget** [orhanerday/open-ai#34]
I've got this error :
Could not resolve: api.openai.com (Could not contact DNS servers)

Any idea ?

Thks

**Comment by orhanerday** [comment]
Hi @gregoirepuge,
Can you share your code?

**Comment by orhanerday** [comment]
Hi @gregoirepuget, 
I'm so sorry but I need more information to fix the issue. 
Please don't hesitate to ask questions to me _(@orhan#3021)_ on our Discord Server https://discord.gg/E5eQzyeU

Closing the issue, reason why; need info.

**Comment by gregoirepuget** [comment]
Perhaps it's because i'm on localhost...

I tried your sample code.
Thanks for your help

**Comment by orhanerday** [comment]
> Perhaps it's because i'm on localhost...
> 
> I tried your sample code. Thanks for your help

It doesn't matter code is executed in localhost. I test it there is no issue;
![image](https://user-images.githubusercontent.com/22305274/209512149-01395e4e-e615-4a0a-b82c-2e29d179443f.png)
Please ask your question with your code part on the discord #help text channel.
