### ISSUE TITLE
Fine-tune pricing as in Python CLI

### ISSUE THREAD

**Issue by inpresif** [orhanerday/open-ai#35]
### Describe the feature or improvement you're requesting

When reading the docs and YT videos on fine-tuning your model, you see the Python CLI displays the pricing of your model you're about to Fine-tune.

Would this be possible with this package as well? So before actually starting the fine-tune, see an estimate of what it is going to cost you, and thén continue with the actual FT, or not.

**Comment by orhanerday** [comment]
Hi @inpresif,
Can you explain more information about Python CLI? And could you please send over the related code part for the python CLI thus I can easily implement it?

**Comment by inpresif** [comment]
Hi, thanks for the reply I appreciate it!
I'm talking about this section here (starts right at the point of showing you the cost) : https://youtu.be/_RTN8CWFUsc?t=295

I have not yet tried that myself, but by the looks of there is that step.

**Comment by orhanerday** [comment]
Oh K. I see. Unfortunately, I can implement only [API references](https://beta.openai.com/docs/api-reference). 
Please contact OpenAI for this feature.

**Comment by inpresif** [comment]
Ok, I'll make a request on their end. Cheers.
