### ISSUE TITLE
Feature Request - Support Stream

### ISSUE THREAD

**Issue by isotropicdesign** [orhanerday/open-ai#36]
### Describe the feature or improvement you're requesting

OpenAI has a great feature called stream (you can see it in action in the playground). I'd like to suggest that this feature be implemented in this library.
https://beta.openai.com/docs/api-reference/completions/create#completions/create-stream

**Comment by orhanerday** [comment]
Thx @isotropicdesign, I'll be working on it.

**Comment by orhanerday** [comment]
Done 🚀 , please check
https://github.com/orhanerday/open-ai#stream-example
