### ISSUE TITLE
Disabling SSL checking in cURL can solve getting "false" as a response

### ISSUE THREAD

**Issue by Furburger** [orhanerday/open-ai#38]
### Describe the bug

This is not a bug per se, but I thought I would share it with other users and the dev team in case it helps.

In another thread, users were reporting that they were getting nothing or "false" back when they were sending a simple Completion like this:

        $open_ai = new OpenAi($open_ai_key);

        $response = $open_ai->completion([
            'model' => 'davinci',
            'prompt' => 'Hello',
            'temperature' => 0.9,
            'max_tokens' => 150,
            'frequency_penalty' => 0,
            'presence_penalty' => 0.6,
        ]);

The issue is now closed, but I found that if you are testing on a local host and are using something like Laragon (which is similar to XAMPP) to host your app or website, the certificates issued are very generic and can cause cURL to fail if it is set to verify the certificate,

To resolve it, you can go to the **OpenAi.php** file in the vendor folder and add
`CURLOPT_SSL_VERIFYPEER => false,` 
to the **sendRequest** function like this:

        $curl_info = [
            CURLOPT_URL => $url,
            CURLOPT_RETURNTRANSFER => true,
            ...
            CURLOPT_HTTPHEADER => $this->headers,
            CURLOPT_SSL_VERIFYPEER => false,
        ];
        
and it no longer tries to verify the SSL certificate. It resolved my issue and so it may help others who encounter a similar issue.

You may want to consider adding it to the next release, but I am unsure of what the implications may be from a SSL point of view, if any? Maybe you could add it as an optional **$opts** parameter for those who are testing on localhosts which they could then remove when in production.

### To Reproduce

Nothing to reproduce

### OS

Windows

### PHP version

PHP 8.1.3

### Library version

v3.3

**Comment by orhanerday** [comment]
I think this is not a common issue, If I get feedback so much about this issue I will be ready to dig into it. So I'll close the issue.

_For SEO;_ **if you getting the same issue please give a 👍**

**Comment by ltanase77** [comment]
I can confirm the issue raised by Furburger. I am not using Laragon or XAMPP. I am on Windows 10, with PHP 8.1.14 installed. I have a Laravel 8 app and I have created a simple Controller for testing embeddings feature, and nothing was returned by the open_ai php  bindings (except false) until I made the changes mentioned by Furburger. Then immediately the result appeared as expected.

**Comment by BlueJ-D** [comment]
Just to Add, I'm also getting 'false' anytime I'm developing on local machine. This is with php serve (v7 & 8), Laravel artisan serve, and in wamp. Always fixed by setting the SSL_verfiy to false in the curl opts. 
I'd suggest a second optional parameter to allow for providing curl settings on our end. This way we could use 'dev' flag to avoid having to edit the src files and risk breaking on upgrade.
