### ISSUE TITLE
The event-Stream feature cannot catch any error.

### ISSUE THREAD

**Issue by tuyenlaptrinh** [orhanerday/open-ai#42]
### Describe the feature or improvement you're requesting

I see completion with stream can not catch error like "Wrong API".
The completion is still working fine with stream and correct API.

**Comment by orhanerday** [comment]
Hi,

I didn't quite catch what mean Wrong API is. Can you give me more specifications about your issue?

Thanks

**Comment by tuyenlaptrinh** [comment]
https://github.com/orhanerday/open-ai#stream-example

I used your example. Everything is working very well. But when I change API key to "Wrong API". Mean just one more character to make it wrong. event message empty and no error from OpenAI. It should be return "Incorrect API key provided: ssk-eSrU****************************************X5Ln. You can find your API key at https://beta.openai.com."

**Comment by orhanerday** [comment]
Could you please provide your code? Please add some `*` to your API key.

**Comment by tuyenlaptrinh** [comment]
Everything same your example. I just put wrong API key.

**Comment by orhanerday** [comment]
Ok, I got you, bro. But I really need your code for understanding the issue 😅

**Comment by tuyenlaptrinh** [comment]
https://www.loom.com/share/48240e831e474588aef2005a2e5a993b

I recorded. I used everything from your example.

**Comment by orhanerday** [comment]
I'll take a look ASAP. 
Thanks

**Comment by tuyenlaptrinh** [comment]
Thank you so much.

**Comment by orhanerday** [comment]
this issue is not related to this library, we need to add more checks for the function of completion and the javascript part. You can also test with this [example](https://github.com/mdn/dom-examples/tree/main/server-sent-events). Therefore there is no code changing at this point, we should only change the readme file. I'll ping you when it's ready. 

I'm closing the issue rn.

Thanks.
