### ISSUE TITLE
return false in request

### ISSUE THREAD

**Issue by RorinL** [orhanerday/open-ai#44]
### Describe the bug

To use this library in thinkphp5, the returned information is false, and nothing is returned to me except false; I have set "set OPENAI_API_KEY=sk-gjtv...."
I am sure there is nothing wrong with my code, if this library is not referenced, then it should directly display an error

### To Reproduce

1

### Code snippets

```JavaScript
<?php

namespace app\index\controller;

use think\Controller;
use Orhanerday\OpenAi\OpenAi;

class Index extends Controller
{
    public function index()
    {
        $open_ai_key = config("openai.OPENAI_API_KEY");
        $open_ai = new OpenAi($open_ai_key);
        //dump($open_ai_key); // have

        // $complete = $open_ai->completion([
        //     "model"   =>  "code-davinci-002",
        //     "prompt"  =>  "",
        //     "temperature" => 0,
        //     "max_tokens" => 64,
        //     "top_p" => 1,
        //     "frequency_penalty" => 0,
        //     "presence_penalty" => 0,
        //     "stop" => ["\"\"\""],
        // ]);
        $complete = $open_ai->completion([
            'model' => 'davinci',
            'prompt' => 'Hello',
            'temperature' => 0.9,
            'max_tokens' => 150,
            'frequency_penalty' => 0,
            'presence_penalty' => 0.6,
        ]);

        dump($complete); //that is "false"
        //return $this->fetch(["msg"=>$complete]);
    }
}
```

### OS

win10

### PHP version

7.4.3

### Library version

3.4

**Comment by orhanerday** [comment]
I think cURL is disabled, Can you check this issue; https://github.com/orhanerday/open-ai/issues/12

**Comment by RorinL** [comment]
@orhanerday Thank you, I will refer to it，cURL is enable

**Comment by RorinL** [comment]
@orhanerday It turned out to be an issue with the ssl certificate [https://github.com/orhanerday/open-ai/issues/12#issuecomment-1379440261](12#issuecomment-1379440261)
