### ISSUE TITLE
No output is coming from openai libaray

### ISSUE THREAD

**Issue by tayyabhafeez006** [orhanerday/open-ai#46]
### Describe the bug

I have write this code but it giving no output and returning bool(false) on var_dump($result);

### To Reproduce

<?php

    require __DIR__ . '/vendor/autoload.php';

    use Orhanerday\OpenAi\OpenAi;

    $open_ai_key = getenv('OPENAI_API_KEY');
    $open_ai = new OpenAi($open_ai_key);
    
    $result = $open_ai->completion([
        'model' => 'text-davinci-003',
        'prompt' => 'Make me a paragraph that summarizes this text for a second-grade student',
        'temperature' => 0.7,
        'max_tokens' => 64,
        "top_p" => 1.0,
        'frequency_penalty' => 0.0,
        'presence_penalty' => 0.0,
    ]);

    echo $result;
    // var_dump($result);
?>

### Code snippets

```JavaScript
<?php

    require __DIR__ . '/vendor/autoload.php';

    use Orhanerday\OpenAi\OpenAi;

    $open_ai_key = getenv('OPENAI_API_KEY');
    $open_ai = new OpenAi($open_ai_key);
    
    $result = $open_ai->completion([
        'model' => 'text-davinci-003',
        'prompt' => 'Make me a paragraph that summarizes this text for a second-grade student',
        'temperature' => 0.7,
        'max_tokens' => 64,
        "top_p" => 1.0,
        'frequency_penalty' => 0.0,
        'presence_penalty' => 0.0,
    ]);

    echo $result;
    // var_dump($result);
?>
```

### OS

Windows

### PHP version

PHP 8.1.0

### Library version

openai v.3.0.1

**Comment by orhanerday** [comment]
Hi, I think this issue is a duplicate, could you check the [related issue](https://github.com/orhanerday/open-ai/issues/12)? 

Thx

**Comment by orhanerday** [comment]
Hi, I think this issue is a duplicate, could you check the [related issue](https://github.com/orhanerday/open-ai/issues/12)? 

Thx.

**Comment by tayyabhafeez006** [comment]
It's solved, Thanks
