### ISSUE TITLE
When I use stream, I sometimes encounter such a problem that the response content starts from a certain sentence and repeats continuously

### ISSUE THREAD

**Issue by yingliu85** [orhanerday/open-ai#50]
### Describe the bug

When I use stream, I sometimes encounter such a problem that the response content starts from a certain sentence and repeats continuously

### To Reproduce

1.The user enters a question to ask
2.use eventSource
3.php code see below

### Code snippets

```JavaScript
$opts = [
            'model' => 'text-davinci-003',
            'prompt' => '你看过《满江红》吗？',
            'temperature' => 0,
            'max_tokens' => 2000,
            'stream' => true,
        ];

        header('Content-type: text/event-stream');
        header('Cache-Control: no-cache');

        $open_ai->completion($opts, function ($curl_info, $data) {
            echo $data . "\n\n";
            echo PHP_EOL;
            ob_flush();
            flush();
            info($data);
            return strlen($data);
        });


前端使用eventSource
```

### OS

linux

### PHP version

php 7.4

### Library version

openai v3.0.1

**Comment by yingliu85** [comment]
sorry,openai v3.4


![1676045401211](https://user-images.githubusercontent.com/121155076/218139918-adc0e67b-3f2f-4759-b4f8-daf12df25f88.png)

**Comment by orhanerday** [comment]
Hi @yingliu85 ,

Can you produce the same test for openai-python? It should be straightforward to make. And please compare responses with my package. I'll be waiting for the results.

**Comment by orhanerday** [comment]
@yingliu85 can you reopen the issue after providing the info?

Now I’ll close the issue,
