### ISSUE TITLE
I get nothing as response

### ISSUE THREAD

**Issue by sebinator** [orhanerday/open-ai#51]
### Describe the bug

get ge nothing in response, when i var_dump, i have a boolean false

test.php:25:boolean false

### To Reproduce

reproduced code

### Code snippets

```JavaScript
$prompt = "Hello";

$complete = $open_ai->completion([
    'model' => 'davinci',
    'prompt' => $prompt,
    'temperature' => 0.7,
    'max_tokens' => 150,
    'frequency_penalty' => 0,
    'presence_penalty' => 0,
]);

var_dump($complete);
```

### OS

windows

### PHP version

8,2

### Library version

openai v3.5

**Comment by orhanerday** [comment]
please check https://github.com/orhanerday/open-ai/issues/12
