### ISSUE TITLE
$openai->completion (singular) works where opanai documentation specifies https://api.openai.com/v1/completions (plural)

### ISSUE THREAD

**Issue by testgonzo** [orhanerday/open-ai#53]
### Describe the bug

The README places links to OpenAI's reference documentation above the fold (at the very beginning), creating the impression that the library's methods have the same name as the path of the OpenAI endpoints.  For example, it may be common for new users of the library to assume Completions are accessed by a method names "completions" such as:

> $openai->completion() (spelled singular)

since the linked OpenAI reference documentation for "completions" endpoint describes endpoint as

POST  https://api.openai.com/v1/completions (spelled plural)

Yet, the library's method is completion (spelled singular)

> $openai->completion() (spelled singular)

This is made clear further down the README, but it's possible many new users will get sidetracked following links to OpenAI's reference and trying to copy the endpoint paths as library method names.  Suggest several possible fixes:

1) At the top of the Readme, calling out the fact method names are described further down the README.

2) Create a prominent table mapping the OpenAI Reference endpoints to the library's methods.

Thnx

 

### To Reproduce

$openai->completion() 

### OS

Linux

### PHP version

PHP 7.4

### Library version

openai v3

**Comment by orhanerday** [comment]
Thanks but I'm not sure this is indispensable, but Ill watch the feedback if we get a lot of requests about this feature. I'll take a look. now pr is closing
