### ISSUE TITLE
why the answer is so short ??  is there any problem?? 

### ISSUE THREAD

**Issue by wuqiu2** [orhanerday/open-ai#54]
### Describe the bug

why the answer is so short ??  is there any problem?? 

### To Reproduce

$open_ai = new OpenAi($open_ai_key);

        $complete = $open_ai->completion([
            'model' => 'text-davinci-003',
            'prompt' => $prompt,
            'temperature' => 0.9,
            //'max_tokens' => 4096,
            'frequency_penalty' => 0,
            'presence_penalty' => 0.6,
        ]);

$prompt = "我家有只狗叫三万，你猜猜它为什么叫这个名字";
I believe the answer is long, but the answer is :
"{"id":"cmpl-.......","object":"text_completion","created":1676702955,"model":"text-davinci-003","choices":[{"text":"？\n\n这可能是你家","index":0,"logprobs":null,"finish_reason":"length"}],"usage":{"prompt_tokens":44,"completion_tokens":16,"total_tokens":60}}
"
why the answer is so short ??  is there any problem?? 

### OS

centos7.2

### PHP version

PHP 7.4

### Library version

openai3

**Comment by orhanerday** [comment]
No, not an issue please increase your `max_tokens` variable

**Comment by wuqiu2** [comment]
> No, not an issue please increase your `max_tokens` variable

thx
I need set max_tokens variable every time ？？ that's not humable.

**Comment by orhanerday** [comment]
@wuqiu2 what does it mean "that's not humable."
