### ISSUE TITLE
When the http code is not equal to 200, an exception need thrown

### ISSUE THREAD

**Issue by zyz954489346** [orhanerday/open-ai#60]
### Describe the feature or improvement you're requesting

Need a way to catch http error,
like this fix in OpenAI.php
![image](https://user-images.githubusercontent.com/23162012/222401506-92a6ecf8-f9dd-4b28-94e5-6cb314493bf4.png)

**Comment by zyz954489346** [comment]
My English is not very good, hope you can understand my meaning  :(..

**Comment by orhanerday** [comment]
Ok I will hold this issue, if we got a few more request about this feature I will implement it. 

Now I closing the issue FYI.

**Comment by zyz954489346** [comment]
> 

If the http exception cannot be caught, then the error code of the API cannot be obtained.
So this change is really necessary.
see https://platform.openai.com/docs/guides/error-codes/api-errors
