### ISSUE TITLE
Call to any function that sends curl request throws exception in v4.5

### ISSUE THREAD

**Issue by mahadsprouttech** [orhanerday/open-ai#62]
### Describe the bug

On calling any function which sends a curl request, e.g completions, we get an exception in v4.5
`curl_getinfo(): supplied resource is not a valid cURL handle resource`
This is because in  the function `sendRequest`,  `curl_getinfo` is being called after `curl_close()` which throws exception thus breaks everything. This makes version 4.5 to not work at all.

### To Reproduce

Call any end point.e.g completions using open-ai version 4.5

### Code snippets

```JavaScript
/**
     * @param string $url
     * @param string $method
     * @param array $opts
     * @return bool|string
     */
    private function sendRequest(string $url, string $method, array $opts = [])
    {
        $post_fields = json_encode($opts);

        if (array_key_exists('file', $opts) || array_key_exists('image', $opts)) {
            $this->headers[0] = $this->contentTypes["multipart/form-data"];
            $post_fields = $opts;
        } else {
            $this->headers[0] = $this->contentTypes["application/json"];
        }
        $curl_info = [
            CURLOPT_URL => $url,
            CURLOPT_RETURNTRANSFER => true,
            CURLOPT_ENCODING => '',
            CURLOPT_MAXREDIRS => 10,
            CURLOPT_TIMEOUT => $this->timeout,
            CURLOPT_FOLLOWLOCATION => true,
            CURLOPT_HTTP_VERSION => CURL_HTTP_VERSION_1_1,
            CURLOPT_CUSTOMREQUEST => $method,
            CURLOPT_POSTFIELDS => $post_fields,
            CURLOPT_HTTPHEADER => $this->headers,
        ];

        if ($opts == []) {
            unset($curl_info[CURLOPT_POSTFIELDS]);
        }

        if (! empty($this->proxy)) {
            $curl_info[CURLOPT_PROXY] = $this->proxy;
        }

        if (array_key_exists('stream', $opts) && $opts['stream']) {
            $curl_info[CURLOPT_WRITEFUNCTION] = $this->stream_method;
        }

        $curl = curl_init();

        curl_setopt_array($curl, $curl_info);
        $response = curl_exec($curl);
        curl_close($curl);

        $info = curl_getinfo($curl);
        $this->curlInfo = $info;

        return $response;
    }
```

### OS

Ubuntu 20.04 or any

### PHP version

PHP 7.4.11 or any

### Library version

openai v4.5

**Comment by orhanerday** [comment]
Can you add your code code please?

**Comment by mahadsprouttech** [comment]
> Can you add your code code please?

https://github.com/orhanerday/open-ai/pull/63
Here you are

**Comment by orhanerday** [comment]
I mean, the code that was written by you. Could you please add that?

**Comment by mahadsprouttech** [comment]
> I mean, the code that was written by you. Could you please add that?

I tried running the ChatGPT example from the Readme in a Laravel controller

```
use Orhanerday\OpenAi\OpenAi;

$open_ai = new OpenAi(env('OPENAI_API_KEY'));

$complete = $open_ai->chat([
   'model' => 'gpt-3.5-turbo',
   'messages' => [
       [
           "role" => "system",
           "content" => "You are a helpful assistant."
       ],
       [
           "role" => "user",
           "content" => "Who won the world series in 2020?"
       ],
       [
           "role" => "assistant",
           "content" => "The Los Angeles Dodgers won the World Series in 2020."
       ],
       [
           "role" => "user",
           "content" => "Where was it played?"
       ],
   ],
   'temperature' => 1.0,
   'max_tokens' => 4000,
   'frequency_penalty' => 0,
   'presence_penalty' => 0,
]);

dd($complete);
```

**Comment by mahadsprouttech** [comment]
@orhanerday will you be releasing a new version ?

**Comment by orhanerday** [comment]
Thanks, I didn't get any error but maybe this error is laravel related. 

Thank you for the pr. I merged

**Comment by orhanerday** [comment]
> @orhanerday will you be releasing a new version ?

I released. 
https://github.com/orhanerday/open-ai/releases/tag/4.6

**Comment by mahadsprouttech** [comment]
> > @orhanerday will you be releasing a new version ?
> 
> I released. https://github.com/orhanerday/open-ai/releases/tag/4.6

Thank you

**Comment by mahadsprouttech** [comment]
> Thanks, I didn't get any error but maybe this error is laravel related.
> 
> Thank you for the pr. I merged

You're welcome. 
Its a PHP issue. Perhaps your PHP version is different than mine ? I tested on PHP 7.4.11. @orhanerday which PHP version did you test on ?
It occurs if any curl function that take cURL resource as parameter like  `curl_getinfo()` or `curl_error()` etc is called after `curl_close()` because the resource has already been closed & cleaned up from the memory.

**Comment by orhanerday** [comment]
> > Thanks, I didn't get any error but maybe this error is laravel related.
> 
> > 
> 
> > Thank you for the pr. I merged
> 
> 
> 
> You're welcome. 
> 
> Its a PHP issue. Perhaps your PHP version is different than mine ? I tested on PHP 7.4.11. @orhanerday which PHP version did you test on ?
> 
> It occurs if any curl function that take cURL resource as parameter like  `curl_getinfo()` or `curl_error()` etc is called after `curl_close()` because the resource has already been closed & cleaned up from the memory.
> 
> 

Yes, it could be, thank you so much for the explanation. 
🚀🚀
