### ISSUE TITLE
Uncaught Error: Call to undefined function env()

### ISSUE THREAD

**Issue by NoBodyButMe** [orhanerday/open-ai#65]
### Describe the bug

I receive this error. I'm running PHP 8.2

### To Reproduce

require_once("vendor/autoload.php"); 
use Orhanerday\OpenAi\OpenAi;

$open_ai = new OpenAi(env('mykey'));

### OS

Hosting

### PHP version

PHP 8.2

### Library version

openai 3.1

**Comment by orhanerday** [comment]
Could you please check the following PR?

https://github.com/orhanerday/open-ai/issues/12


Please re-open the issue it's not related the issue 12.
