### ISSUE TITLE
Request Error:Failed to connect to api.openai.com port 443 after 21066 ms: Timed out

### ISSUE THREAD

**Issue by haotianyuhuang** [orhanerday/open-ai#70]
### Describe the bug

When I use a third-party Python library for OpenAI, it can return results normally. However, when I run PHP, it returns false. When I checked with curl_errno(), I found the error mentioned above. Both situations are under the same network conditions, and I have ruled out the issue of SSL certificate expiration. What could be the problem?

### To Reproduce

![image](https://user-images.githubusercontent.com/93363328/224562628-2fec8a68-3045-4124-9847-bab26c73e035.png)

### OS

Windows

### PHP version

php 8.2

### Library version

4.7

**Comment by haotianyuhuang** [comment]
Sorry for bothering you, the problem has been resolved. I carefully checked your documentation and found out that I needed to set up a proxy.

**Comment by haotianyuhuang** [comment]
Sorry for bothering you, the problem has been resolved. I carefully checked your documentation and found out that I needed to set up a proxy.

**Comment by orhanerday** [comment]
Please check 

https://github.com/orhanerday/open-ai/issues/44#issuecomment-1399185556

**Comment by orhanerday** [comment]
This is perfect, I think you called the [Use Proxy method](https://github.com/orhanerday/open-ai#use-proxy) for solving issues,


Closing now.
