### ISSUE TITLE
GPT-3.5-Turbo logit_bias parameter

### ISSUE THREAD

**Issue by PomzedCommunication** [orhanerday/open-ai#72]
### Describe the bug

Hi,

First of all thanks for your work on this.
I encounter a problem when i try to send an object with various tokenized words with their bias with the "logit_bias" parameter. (https://platform.openai.com/docs/api-reference/chat/create#chat/create-logit_bias)

### To Reproduce

1. Use your quickstart template
2. Add the "logit_bias" parameter and any kind of json object, or even 'null' which from the doc is the accepted default.
3. The response is an error message stating that whatever we put as a value for "logit_bias" is not of type 'object' - 'logis_bias'

### Code snippets

```JavaScript
<?php

require __DIR__ . '/vendor/autoload.php'; // remove this line if you use a PHP Framework.

use Orhanerday\OpenAi\OpenAi;

$open_ai_key = getenv('OPENAI_API_KEY');
$open_ai = new OpenAi($open_ai_key);

$complete = $open_ai->chat([
   'model' => 'gpt-3.5-turbo',
   'messages' => [
       [
           "role" => "system",
           "content" => "You are a helpful assistant."
       ],
       [
           "role" => "user",
           "content" => "Who won the world series in 2020?"
       ],
       [
           "role" => "assistant",
           "content" => "The Los Angeles Dodgers won the World Series in 2020."
       ],
       [
           "role" => "user",
           "content" => "Where was it played?"
       ],
   ],
   'temperature' => 1.0,
   'max_tokens' => 4000,
   'frequency_penalty' => 0,
   'presence_penalty' => 0,
   'logit_bias' => null // or { 3789: 10 } or anything of the sort
]);

var_dump($complete);
```

### OS

Windows

### PHP version

PHP 8.1

### Library version

open-ai v4.7.1

**Comment by orhanerday** [comment]
Hi @PomzedCommunication,
Could you please reproduce the same steps on openai python library or curl?

**Comment by orhanerday** [comment]
Ok, I think this issue is not related to my library.
