### ISSUE TITLE
Chat GTP 4  model integration

### ISSUE THREAD

**Issue by umeshEtelligense** [orhanerday/open-ai#73]
### Describe the feature or improvement you're requesting

I need to integrate Chat GTP 4  model in this repo, How can I do this?
I was trying but didn't get any response from API.
Please let me know when you are planning to integrate the latest Chat GPT4 model.
I will appreciate you if you respond to me.
Thanks

### Additional context

I need to integrate Chat GTP 4  model in this repo, How can I do this?
I was trying but didn't get any response from API.
Please let me know when you are planning to integrate the latest Chat GPT4 model.
I will appreciate you if you respond to me.
Thanks

**Comment by orhanerday** [comment]
Join API waitlist 

**https://openai.com/waitlist/gpt-4-api**

**Comment by orhanerday** [comment]
The library already supports GPT-4, please change the model;
```php
....
$chat = $open_ai->chat([
    'model' => 'gpt-4',
    ....
    
  ....
  ```
