### ISSUE TITLE
How to get only content in output

### ISSUE THREAD

**Issue by Sylvesterx1** [orhanerday/open-ai#77]
### Describe the bug

I write controller CI4:
   

     public function openAIPost()
        {
            $response = array();
            if ($this->request->getMethod() === 'post') {
                $question = $this->request->getPost('question');
                $open_ai_key = getenv('OPENAI_API_KEY');
                $open_ai = new OpenAi($open_ai_key);
                $complete = $open_ai->chat([
                    'model' => 'gpt-3.5-turbo',
                    'messages' => [
                        [
                            "role" => "user",
                            "content" => $question
                        ]
                    ],
                    'temperature' => 1.0,
                    'max_tokens' => 10,
                    'frequency_penalty' => 0,
                    'presence_penalty' => 0,
                ]);
                $response['complete'] = $complete;
            }
            echo json_encode($response);
        }

But I get in output:

    {"id":"chatcmpl-6xxhQ2FLm08VhE8KKHsTpilkvpMTS","object":"chat.completion","created":1679748856,"model":"gpt-3.5-turbo-0301","usage":{"prompt_tokens":9,"completion_tokens":10,"total_tokens":19},"choices":[{"message":{"role":"assistant","content":"This is a test of the AI language model."},"finish_reason":"length","index":0}]}

### To Reproduce

Can you help us How to get only content from response?

### OS

macOS

### PHP version

8.2

### Library version

openai v.3.0.1

**Comment by orhanerday** [comment]
Hi decode the response and access the content

```php
<?php
$j = '{"id":"chatcmpl-6xxhQ2FLm08VhE8KKHsTpilkvpMTS","object":"chat.completion","created":1679748856,"model":"gpt-3.5-turbo-0301","usage":{"prompt_tokens":9,"completion_tokens":10,"total_tokens":19},"choices":[{"message":{"role":"assistant","content":"This is a test of the AI language model."},"finish_reason":"length","index":0}]}';

$d = json_decode($j);

echo($d->choices[0]->message->content);
```

Note that, basic PHP knowledge is required before using this library.
