### ISSUE TITLE
PHPStan shows parameter error

### ISSUE THREAD

**Issue by ronaldrupp** [orhanerday/open-ai#78]
### Describe the bug

PHPStan shows error:
Parameter #2 $stream of method Orhanerday\OpenAi\OpenAi::chat() expects null, Closure given.  

Secondary parameter $stream of chat method is typed null.

### To Reproduce

1. use PHPStan Level 5
2. run it

### Code snippets

```JavaScript
$open_ai->chat($options, function ($curl_info, $data) {
    echo $data . PHP_EOL;
    echo PHP_EOL;
    ob_flush();
    flush();
    return strlen($data);
});
```

### OS

macOS

### PHP version

PHP 8.0

### Library version

openai V4.7.1

**Comment by orhanerday** [comment]
You should handle the error messages, but no worries, I already add that handling please check;  https://github.com/orhanerday/ChatGPT/blob/b326bbf82299c1267e21cd182c02ea21660fb57f/event-stream.php#L51, 

```php

$complete = $open_ai->chat($opts, function ($curl_info, $data) use (&$txt) {
    if ($obj = json_decode($data) and $obj->error->message != "") { 
        error_log(json_encode($obj->error->message)); // <- you can bind this message to toastr etc.
    } else {
        echo $data;
        $clean = str_replace("data: ", "", $data);
        $arr = json_decode($clean, true);
        if ($data != "data: [DONE]\n\n" and isset($arr["choices"][0]["delta"]["content"])) {
            $txt .= $arr["choices"][0]["delta"]["content"];
        }
    }

    echo PHP_EOL;
    ob_flush();
    flush();
    return strlen($data);
});



```
