### ISSUE TITLE
Markdown while typing possible?

### ISSUE THREAD

**Issue by R3dRidl3** [orhanerday/open-ai#79]
### Describe the feature or improvement you're requesting

Well I got this beauty of an package working. But I run into 1 problem I cannot seem to get my head around.
I am working with the SSE and that works fine, i get all the bits and pieces and I get it in a div.
But when ChatGPT is outputting markdown styled content (like a table), I cannot apply markdown while it's still "typing".
I can only manage to do this after ChatGPT is done.

Can anybody share a light on this?

**Comment by orhanerday** [comment]
Could you please ask this question on our discord server? Check readme for the invite URL
