### ISSUE TITLE
Adding more capabilities

### ISSUE THREAD

**Issue by oliverbj** [orhanerday/open-ai#8]
Hi there!

First of all, what a great package! Thank you for creating this.

I was wondering if you'd be open to any PR on the below areas:

- Files
- Fine tuning

I would like to extend the package so we could upload training files and ultimately fine-tune also.

Let me know :)

**Comment by orhanerday** [comment]
Hi, @oliverbj file uploading is shipped. 🚀 🚀 🚀 🚀 🚀

**Comment by oliverbj** [comment]
@orhanerday This is awesome - thanks for pushing this out so quickly. Did you ever get a chance to look at Fine Tuning? (Docs: https://beta.openai.com/docs/api-reference/fine-tunes) 

Again, happy to contribute with a PR if needed!

**Comment by orhanerday** [comment]
Sorry I forgot that part. Fine tuning similar to file upload. I’ll check tomorrow. UTC 14:00 🕑 
If I need help I’ll touch thanks 🙏

**Comment by oliverbj** [comment]
> Sorry I forgot that part. Fine tuning similar to file upload, so seem easy. I’ll check tomorrow. UTC 14:00 🕑 If I need help I’ll touch thanks 🙏

Really appreciate you taking the time to do this - thank you!!!

**Comment by orhanerday** [comment]
Your welcome @oliverbj,
I create [PR](https://github.com/orhanerday/open-ai/pull/10) could you please review it?

**Comment by orhanerday** [comment]
Your welcome @oliverbj ,
I create a [PR](https://github.com/orhanerday/open-ai/pull/11) could you please review it?

**Comment by oliverbj** [comment]
Just reviewed it, and it looks good from my end! Thanks!

**Comment by orhanerday** [comment]
Code shipped to packagist.

Have fun with v2.1 y'all 🚀🚀🚀

![CelebrationCelebrateGIF](https://user-images.githubusercontent.com/22305274/170875049-ff6aa0f8-35ea-41e6-b771-69cbb08cddb0.gif)
