### ISSUE TITLE
Request batching

### ISSUE THREAD

**Issue by dfynest** [orhanerday/open-ai#84]
### Describe the feature or improvement you're requesting

From documentation it seems there is no option for batching requests to avoid hitting limit rate?

OpenAI refers to request batching and has given code example in python (https://platform.openai.com/docs/guides/rate-limits/error-mitigation). Would be useful to do anything similar with this package.

When I try to include several messages in a single request it responds with a single “choice” that uses all the messages as context rather than one response per message.

The OpenAI example below is specifically for the completion endpoint rather than the chat endpoint. However chat endpoint is probably way more desirable for request batching, due to current limit of 3 RPM and 1/10 of completion endpoint price.

UPDATE: After doing bit of research there doesn't seem to be viable options to do batching for ChatCompletion endpoints. At least that's what I've read on the OpenAi forums. There are some workarounds though. Here are links to the posts:
- https://community.openai.com/t/batching-with-chatcompletion-not-possible-like-it-was-in-completion/81647/10
- https://community.openai.com/t/batching-with-chatcompletion-endpoint/137723

### Additional context

OpenAI official batching example for completion endpoint using Python:

`import openai  # for making OpenAI API requests
 
 
num_stories = 10
prompts = ["Once upon a time,"] * num_stories
 
# batched example, with 10 story completions per request
response = openai.Completion.create(
    model="curie",
    prompt=prompts,
    max_tokens=20,
)
 
# match completions to prompts by index
stories = [""] * len(prompts)
for choice in response.choices:
    stories[choice.index] = prompts[choice.index] + choice.text
 
# print stories
for story in stories:
    print(story)`

**Comment by orhanerday** [comment]
I couldn't locate the cURL reference. Can you please reopen the issue if you find it?
