### ISSUE TITLE
Variable $txt does not include initial parts of text

### ISSUE THREAD

**Issue by keradzlopuki** [orhanerday/open-ai#86]
### Describe the bug

I'm having an issue where the variable $txt is not including the initial parts of the text. Instead of "Hello world", it only contains "lo world". This is the code that I'm using:
```php
header('Content-type: text/event-stream');
header('Cache-Control: no-cache');
$txt = "";
$complete = $open_ai->chat($opts, function ($curl_info, $data) use (&$role, &$txt, &$contentId) {
    if ($obj = json_decode($data) and $obj->error->message != "") {
        error_log(json_encode($obj->error->message));
    } else {
        echo $data;
        $clean = str_replace("data: ", "", $data);
        $arr = json_decode($clean, true);

        if ($data != "data: [DONE]\n\n" and isset($arr["choices"][0]["delta"]["content"])) {
            $txt .= $arr["choices"][0]["delta"]["content"];
        }
    }

    echo PHP_EOL;
    ob_flush();
    flush();
    return strlen($data);
});
```

I'm not sure why $txt is not including the initial parts of the text. Can someone help me with this issue?

### To Reproduce

1.     Execute the code provided in the question.
2.     Ensure that the $open_ai object is properly instantiated and configured with the appropriate options.
3.     Trigger the function that calls the $open_ai->chat() method.

    Check the output and observe that the variable $txt does not include the initial parts of the text.

### OS

Ubuntu

### PHP version

7.4.21

### Library version

openai 4.7.1

**Comment by boravsbora** [comment]
I'm literally having the same issue. Tried stepping through the code and I'm having difficulty pin-pointing the problem. 

If it's helpful, in some instances the first word of the output is not omitted but I'm not certain as to why. Also, everything that is being passed directly from the API to screen is displaying/printing correctly, the problem occurs only when the output is written to the database.

I believe the issue is with this line:

if ($data != "data: [DONE]\n\n" and isset($arr["choices"][0]["delta"]["content"])) {
			$txt .= $arr["choices"][0]["delta"]["content"];
}

**Comment by aytaceminoglu** [comment]
any solution?

**Comment by suage** [comment]
I found _json_decode_ returns NULL. I'm guessing this must be cause of  _$txt_ does not include initial parts of text 

I found _$clean_ variable seem to be valid json, BUT  _json_decode($clean, true)_ returns NULL. 
_json_last_error_ returns JSON_ERROR_SYNTAX.
I still don't know the cause of the syntax error.

**Comment by orhanerday** [comment]
Sorry for the delayed response, is this an ongoing issue? Everything is perfectly worked on `https://github.com/orhanerday/ChatGPT`. Can you guys reference it?
