### ISSUE TITLE
HTML Format

### ISSUE THREAD

**Issue by emresaracoglu** [orhanerday/open-ai#90]
### Describe the feature or improvement you're requesting

Hello, I want to receive the incoming response in HTML format. Is this possible? thank you

**Comment by orhanerday** [comment]
Please be more specific, you can provide some examples.

**Comment by emresaracoglu** [comment]
Sorry for the late response, I just realized.
The answers given on the ChatGPT official website are created in markdown format. Is it possible to get the answer to the question we asked with this library in markdown or HTML format? Because sometimes there are tables in the answers or the program-language is given. You know it is difficult to read when given in a plain text format. If it can provide HTML or markdown response by ChatGPT, we would be happy to see it in your library.

**Comment by bashar94** [comment]
@emresaracoglu You can write it in the prompt to generate the output in specific markup and the output will show you the markup as a string. It is not anything to do with the library, get your output as you like and render it accordingly. Your prompt should do the work!

**Comment by emresaracoglu** [comment]
> @emresaracoglu You can write it in the prompt to generate the output in specific markup and the output will show you the markup as a string. It is not anything to do with the library, get your output as you like and render it accordingly. Your prompt should do the work!

Hi @bashar94 Thank you for your message, i can use it as I want right now
