### ISSUE TITLE
The data was randomly merged

### ISSUE THREAD

**Issue by Max-Liu** [orhanerday/open-ai#91]
### Describe the bug

When I've parsed the data and exported it to the front end, it should look something like this:
{"code":200,"message":"OK","data":"\u662f"}

Sometimes, however, it concatenates multiple results, which causes the front end to fail to parse the data:
{"code":200,"message":"OK","data":"\u662f"}
{"code":200,"message":"OK","data":"\u7684"}

### To Reproduce

What happens is very random, if I add random sleep to the callback function, or if I add more PHP_EOL, the probability of it happening will decrease

### Code snippets

```JavaScript
$this->chat($option, function ($curl_info, string $data) {
                if (! str_contains($data, 'data: [DONE]')) {
                    $result = ChatStreamResponse::parse($data);

                    if ($result) {
                        $this->buffer[] = $result->content;
                        /**
                         * json encode the response and echo it
                         * {"code":200,"message":"OK","data":"\u662f"}
                         */
                        echo AbstractResponse::sendOK($result->content)->content();
                        echo PHP_EOL;
                        ob_flush();
                        flush();
                    }
                }
                return strlen($data);
            });
```

### OS

macOS

### PHP version

php8.1

### Library version

openai v4.7.1

**Comment by orhanerday** [comment]
Could you please use [this](https://github.com/orhanerday/ChatGPT) reference on your work? I can't support to implementation process.
