### ISSUE TITLE
Is there any strategy for performing throttled parallel calls using this library?

### ISSUE THREAD

**Issue by vesper8** [orhanerday/open-ai#92]
### Describe the feature or improvement you're requesting

I was just looking at this here https://github.com/openai/openai-cookbook/blob/main/examples/api_request_parallel_processor.py

It essentially allows to queue/batch multiple calls to be run in parallel while observing the rate limits.. super useful if you need to run many calls at once and don't want to run into errors. Would something like this be feasible in PHP I wonder?

**Comment by orhanerday** [comment]
I couldn't locate the cURL reference. Can you please reopen the issue if you find it?
