### ISSUE TITLE
chat api sometimes unreasonably "exceeds" 4000 completion tokens

### ISSUE THREAD

**Issue by WilliamLSang** [orhanerday/open-ai#93]
### Describe the bug

I'm having an issue with the chat api saying I am exceeding the maximum length of 4000 tokens despite my request clearly not exceeding even 300 tokens. I tried the exact same request using python's openai api and it worked fine. It seems past a certain point in the length of conversation will cause a bug in the count of completion token.

### To Reproduce

This is the error after running the code:
  ["error"]=>
  object(stdClass)#28 (4) {
    ["message"]=>
    string(189) "This model's maximum context length is 4097 tokens. However, you requested 4111 tokens (111 in the messages, 4000 in the completion). Please reduce the length of the messages or completion."
    ["type"]=>
    string(21) "invalid_request_error"
    ["param"]=>
    string(8) "messages"
    ["code"]=>
    string(23) "context_length_exceeded"
  }
}

### Code snippets

```JavaScript
require_once __DIR__ . '/vendor/autoload.php';
$dotenv = Dotenv\Dotenv::createImmutable(__DIR__);
$dotenv->load();
use Orhanerday\OpenAi\OpenAi;

$open_ai = new OpenAi($_ENV['OPENAI_API_KEY']);
$chat = $open_ai->chat([
    'model' => 'gpt-3.5-turbo',
    'messages' => [
        [
            "role"=>"system",
            "content"=>"summarize conversation within 40 words"
        ],
        [
            "role"=>"user",
            "content"=>" Anna: Hi my name is Anna User: hello how do i cook an egg? Anna: To cook an egg, bring a pot of water to boil, reduce heat, and gently add an egg for 3-5 minutes. User: what about a potato? Anna: To cook a potato, scrub it clean, poke a few holes in it, and bake in the oven at 400°F for about an hour, or until tender."
        ]
    ],
    'temperature' => 1.0,
    'max_tokens' => 4000,
    'frequency_penalty' => 0,
    'presence_penalty' => 0,
 ]);

$d = json_decode($chat);
var_dump($d);
// Get Content
echo($d->choices[0]->message->content);
```

### OS

Windows

### PHP version

PHP 8.2.4

### Library version

openai V4.7

**Comment by orhanerday** [comment]
Sure, thanks.
