### ISSUE TITLE
The CURLOPT_HTTP_VERSION should be CURL_HTTP_VERSION_2_0, not CURL_HTTP_VERSION_1_1

### ISSUE THREAD

**Issue by xwmhmily** [orhanerday/open-ai#97]
### Describe the bug

The CURLOPT_HTTP_VERSION  in OpenAi.php, line 523 is CURL_HTTP_VERSION_1_1, which makes it's not possbile to resposd with stream, should be CURL_HTTP_VERSION_2_0。

### To Reproduce

Open the OpenAi.php
Goto line 523

### OS

Linux

### PHP version

8

### Library version

4.7

**Comment by orhanerday** [comment]
I think this is related to your local machine. Can you try with docker?
