### ISSUE TITLE
Function Calling?

### ISSUE THREAD

**Issue by frishtik** [orhanerday/open-ai#98]
### Describe the feature or improvement you're requesting

Hi there! Glad to be using your wonderful project!
As you know for sure, OpenAI released some updates to the API, including Function Calling. 
Is it possible to use Function Calling with the project right now?
If not, could you possibly add it?
Thanks anyway. Much appreciated work.

**Comment by orhanerday** [comment]
I couldn't locate the cURL reference. Can you please reopen the issue if you find it?

**Comment by lakshaysethi** [comment]
curl https://api.openai.com/v1/chat/completions \
-H "Content-Type: application/json" \
-H "Authorization: Bearer $OPENAI_API_KEY" \
-d '{
  "model": "gpt-3.5-turbo",
  "messages": [
    {
      "role": "user",
      "content": "What is the weather like in Boston?"
    }
  ],
  "tools": [
    {
      "type": "function",
      "function": {
        "name": "get_current_weather",
        "description": "Get the current weather in a given location",
        "parameters": {
          "type": "object",
          "properties": {
            "location": {
              "type": "string",
              "description": "The city and state, e.g. San Francisco, CA"
            },
            "unit": {
              "type": "string",
              "enum": ["celsius", "fahrenheit"]
            }
          },
          "required": ["location"]
        }
      }
    }
  ],
  "tool_choice": "auto"
}'


![image](https://github.com/orhanerday/open-ai/assets/45325278/ac2ea35d-5d32-49c0-9c03-008a95cbe44a)
from 
https://platform.openai.com/docs/api-reference/chat/create
